/*
 * Automatically generated by PATINA; edits will be discarded on rebuild.
 * (Most header files phrase this 'Do not edit.'; be warned accordingly.)
 *
 * Generated: 2024-04-26 19:32:39.677255.
 */

pub const SIMPLESPI_ADDR: u32 = 0x800 ; // 2048
pub const OUTPUTPORT_ADDR: u32 = 0x1000 ; // 4096
pub const RESET_VECTOR: u32 = 0x0; // 0
pub const DATE_STAMP: &str = "2024-04-26 19:32:39.677327";
