[build]
target = "riscv32i-unknown-none-elf"

[target.rv32-hapenny]
rustflags = [
    "-C", "link-arg=-Tlink.x",
]

[target.riscv32i-unknown-none-elf]
rustflags = [
    "-C", "relocation-model=pie",
    "-C", "link-arg=-Tmemory.x",
]
runner = "cargo objcopy --release -- -O binary"


[env]
# CARGO_TARGET_DIR="."
