[build]
target = "riscv32i-unknown-none-elf"

[target.riscv32i-unknown-none-elf]
runner = "cargo objdump --release --bin spi_test -- --disassemble --no-show-raw-insn"

# nice and small can be reloacated.
rustflags = [
 "-C", "relocation-model=pie",
 "-C", "link-arg=-Tmemory.x",
 "-C", "embed-bitcode=y",
 "-C", "lto=fat",
]
