/*
 * Automatically generated by LUNA; edits will be discarded on rebuild.
 * (Most header files phrase this 'Do not edit.'; be warned accordingly.)
 *
 * Generated: 2024-02-10 15:56:37.584099.
 */

MEMORY {
    ram : ORIGIN = 0x00000000, LENGTH = 0x00004000
    bootrom : ORIGIN = 0x00004000, LENGTH = 0x00001000
}

SECTIONS {
}

REGION_ALIAS("REGION_TEXT", ram);
REGION_ALIAS("REGION_RODATA", ram);
REGION_ALIAS("REGION_DATA", ram);
REGION_ALIAS("REGION_BSS", ram);
REGION_ALIAS("REGION_HEAP", ram);
REGION_ALIAS("REGION_STACK", ram);
