/*
 * Automatically generated by PATINA; edits will be discarded on rebuild.
 * (Most header files phrase this 'Do not edit.'; be warned accordingly.)
 *
 * Generated: 2025-02-15 21:01:16.665639.
 */

/// BidiUart
pub const BIDIUART_ADDR: u32 = 0x4000 ; // 16384

/// WarmBoot
pub const WARMBOOT_ADDR: u32 = 0x6000 ; // 24576

/// Watchdog
pub const WATCHDOG_ADDR: u32 = 0x8000 ; // 32768

/// SimpleSPI
pub const SIMPLESPI_ADDR: u32 = 0xA000 ; // 40960

/// Reset Vector
pub const RESET_VECTOR: u32 = 0x2000; // 8192
/// Date stamp when this file was generated
pub const DATE_STAMP: &str = "2025-02-15 21:01:16.665723";
