/*
 * Automatically generated by PATINA; edits will be discarded on rebuild.
 * (Most header files phrase this 'Do not edit.'; be warned accordingly.)
 *
 * Generated: 2024-09-01 09:58:43.055747.
 */

/// BidiUart
pub const BIDIUART_ADDR: u32 = 0x800 ; // 2048

/// Reset Vector
pub const RESET_VECTOR: u32 = 0x400; // 1024
/// Date stamp when this file was generated
pub const DATE_STAMP: &str = "2024-09-01 09:58:43.055818";
