/*
 * Automatically generated by PATINA; edits will be discarded on rebuild.
 * (Most header files phrase this 'Do not edit.'; be warned accordingly.)
 *
 * Generated: 2025-01-30 07:00:37.661857.
 */

MEMORY {
    MEMORY : ORIGIN = 0x00000000, LENGTH = 0x2800
    BOOTMEM : ORIGIN = 0x00004000, LENGTH = 0x400
