/*
 * Automatically generated by PATINA; edits will be discarded on rebuild.
 * (Most header files phrase this 'Do not edit.'; be warned accordingly.)
 *
 * Generated: 2024-05-09 22:56:26.926646.
 */

pub const BIDIUART_ADDR: u32 = 0x8000 ; // 32768
pub const WARMBOOT_ADDR: u32 = 0xC000 ; // 49152
pub const OUTPUTPORT_ADDR: u32 = 0x10000 ; // 65536
pub const INPUTPORT_ADDR: u32 = 0x14000 ; // 81920
pub const SIMPLESPI_ADDR: u32 = 0x18000 ; // 98304
pub const RESET_VECTOR: u32 = 0x4000; // 16384
pub const DATE_STAMP: &str = "2024-05-09 22:56:26.926744";
