/*
 * Automatically generated by PATINA; edits will be discarded on rebuild.
 * (Most header files phrase this 'Do not edit.'; be warned accordingly.)
 *
 * Generated: 2024-05-10 11:52:09.771685.
 */

pub const BIDIUART_ADDR: u32 = 0x28000 ; // 163840
pub const SIMPLESPI_ADDR: u32 = 0x30000 ; // 196608
pub const RESET_VECTOR: u32 = 0x20000; // 131072
pub const DATE_STAMP: &str = "2024-05-10 11:52:09.771762";
